require:
  - rubocop/cop/internal_affairs
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake
AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'sig/*'
    - 'Gemfile'
    - 'Gemfile.lock'
  TargetRubyVersion: 2.6
  SuggestExtensions: false
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma